export const AVANTI_WEST_COAST = [
	'Birmingham International',
	'Carlisle',
	'Coventry',
	'Crewe (& Chester and North Wales)',
	'Lancaster',
	'Macclesfield',
	'Oxenholme Lake District',
	'Penrith North Lakes',
	'Preston',
	'Rugby',
	'Runcorn',
	'Stafford',
	'Stockport',
	'Stoke-on-Trent',
	'Warrington Bank Quay',
	'Wigan North Western',
]

export const C2C = [
	'Barking',
	'Basildon',
	'Benfleet',
	'Chafford Hundred',
	'Chalkwell',
	'Dagenham Dock',
	'East Tilbury',
	'London Fenchurch Street',
	'Grays',
	'Laindon',
	'Leigh-on-Sea',
	'Limehouse',
	'London Liverpool Street',
	'Ockendon',
	'Pitsea',
	'Purfleet',
	'Rainham',
	'Shoeburyness',
	'Southend Central',
	'Southend East',
	'Stanford-le-Hope',
	'Stratford',
	'Thorpe Bay',
	'Tillbury Town',
	'Upminster',
	'Westcliff',
	'West Ham',
	'West Horndon',
]

export const CHILTERN_RAILWAYS = [
	'Amersham',
	'Aylesbury',
	'Aylesbury Vale Parkway',
	'Banbury',
	'Beaconsfield',
	'Bicester North',
	'Bicester Village',
	'Birmingham Moor Street',
	'Chalfont & Latimer',
	'Chorleywood',
	'Denham',
	'Denham Golf Club',
	'Dorridge',
	'Gerrards Cross',
	'Great Missenden',
	'Haddenham & Thame Parkway',
	'Hagley',
	'Harrow-on-the-Hill',
	'Hatton',
	'High Wycombe',
	'Islip',
	'Kings Sutton',
	'Lapworth',
	'Leamington Spa',
	'Little Kimble',
	'London Marylebone',
	'Monks Risborough',
	'Northolt Park',
	'Oxford Parkway',
	'Princes Risborough',
	'Rickmansworth',
	'Saunderton',
	'Seer Green & Jordans',
	'Solihull',
	'South Ruislip',
	'Stoke Mandeville',
	'Sudbury & Harrow Road',
	'Sudbury Hill Harrow',
	'Warwick',
	'Warwick Parkway',
	'Wembley Stadium',
	'Wendover',
	'West Ruislip',
]

export const EAST_MIDLANDS_RAILWAY = [
	'Wellingborough',
	'Kettering',
	'Corby',
	'Market Harborough',
	'Leicester',
	'Melton Mowbray',
	'Oakham',
	'Stamford',
	'Narborough',
	'Hinckley',
	'Loughborough',
	'East Midlands Parkway',
	'Long Eaton',
	'Derby',
	'Kidsgrove',
	'Chesterfield',
	'Sheffield',
	'Beeston',
	'Nottingham',
	'Alfreton',
	'Sleaford',
	'Boston',
	'Skegness',
]

export const GREATER_ANGLIA = [
	[
		'Acle',
		'Alresford (Essex)',
		'Althorne (Essex)',
		'Angel Road',
		'Attleborough',
		'Audley End',
		'Battlesbridge',
		'Beccles',
		'Berney Arms',
		'Billericay',
		'Bishops Stortford',
		'Braintree',
		'Braintree Freeport',
		'Brampton (Suffolk)',
		'Brandon',
		'Brimsdown',
		'Broxbourne',
		'Brundall',
		'Brundall Gardens',
		'Buckenham',
		'Bures',
		'Burnham-on-Crouch',
		'Bury St Edmunds',
		'Cambridge',
		'Cambridge North',
		'Cantley',
		'Chappel & Wakes Colne',
		'Chelmsford',
		'Cheshunt',
		'Clacton-on-Sea',
		'Colchester',
		'Colchester Town',
		'Cressing (Essex)',
		'Cromer',
		'Darsham',
		'Derby Road (Ipswich)',
		'Diss',
		'Dovercourt',
		'Downham Market',
		'Dullingham',
		'Eccles Road',
		'Elmswell',
		'Elsenham (Essex)',
		'Ely',
		'Enfield Lock',
		'Felixstowe',
		'Frinton-on-Sea',
		'Great Bentley',
		'Great Chesterford',
		'Great Yarmouth',
		'Gunton',
		'Haddiscoe',
		'Halesworth',
		'Harling Road',
		'Harlow Mill',
		'Harlow Town',
		'Harwich International',
		'Harwich Town',
		'Hatfield Peverel',
		'Hertford East',
		'Hockley',
		'Hoveton & Wroxham',
		'Hythe (Essex)',
		'Ingatestone',
		'Ipswich',
		'Kelvedon',
		'Kennett',
		'Kings Lynn',
		'Kirby Cross',
		'Lakenheath',
		'Lea Bridge',
		'Lingwood',
		'Littleport',
		'London Liverpool Street',
		'Lowestoft',
		'Manea',
		'Manningtree',
		'March',
		'Marks Tey',
		'Melton (Suffolk)',
		'Meridian Water',
		'Mistley',
		'Needham Market',
		'Newmarket',
		'Newport (Essex)',
		'North Fambridge',
		'North Walsham',
		'Northumberland Park',
		'Norwich',
		'Oulton Broad North',
		'Oulton Broad South',
		'Peterborough',
		'Ponders End',
		'Prittlewell',
		'Rayleigh',
		'Reedham (Norfolk)',
		'Rochford',
		'Roughton Road',
		'Roydon',
		'Rye House',
		'Salhouse',
		'Sawbridgeworth',
		'Saxmundham',
		'Shelford (Cambs)',
		'Shenfield',
		'Sheringham',
		'Shippea Hill',
		'Soham',
		'Somerleyton',
		'South Woodham Ferrers',
		'Southend Airport',
		'Southend Victoria',
		'Southminster',
		'Spooner Row',
		'St Margarets (Herts)',
		'Stansted Airport',
		'Stansted Mountfitchet',
		'Stowmarket',
		'Stratford (London)',
		'Sudbury (Suffolk)',
		'Thetford',
		'Thorpe-le-Soken',
		'Thurston',
		'Tottenham Hale',
		'Trimley',
		'Waltham Cross',
		'Walton-on-the-Naze',
		'Ware (Herts)',
		'Waterbeach',
		'Watlington',
		'Weeley',
		'West Runton',
		'Westerfield',
		'White Notley',
		'Whittlesea',
		'Whittlesford Parkway',
		'Wickford',
		'Wickham Market',
		'Witham',
		'Wivenhoe',
		'Woodbridge',
		'Worstead',
		'Wrabness',
		'Wymondham',
	],
]

export const GREAT_WESTERN_RAILWAY = [
	'Aldermaston',
	'Appleford',
	'Ascott-under-Wychwood',
	'Ash',
	'Ashchurch for Tewkesbury',
	'Avoncliff',
	'Avonmouth',
	'Barnham',
	'Barnstaple',
	'Bath Spa',
	'Bedminster',
	'Bedwyn',
	'Bere Alston',
	'Bere Ferrers',
	'Betchworth',
	'Blackwater',
	'Bodmin Parkway',
	'Bourne End',
	'Bradford-on-Avon',
	'Bridgwater',
	'Bristol Parkway',
	'Bruton',
	'Bugle',
	'Burnham',
	'Calstock',
	'Cam and Dursley',
	'Camborne',
	'Carbis Bay',
	'Castle Bar Park',
	'Castle Cary',
	'Causeland',
	'Chapelton',
	'Charlbury',
	'Cheltenham Spa',
	'Chetnole',
	'Chichester',
	'Chilworth',
	'Chippenham',
	'Cholsey',
	'Clifton Down',
	'Combe',
	'Cookham',
	'Coombe Junction Halt',
	'Copplestone',
	'Cosham',
	'Crediton',
	'Crowthorne',
	'Culham',
	'Dawlish',
	'Dawlish Warren',
	'Devonport',
	'Didcot Parkway',
	'Digby and Sowton',
	'Dilton Marsh',
	'Dockyard',
	'Dorchester West',
	'Dorking Deepdene',
	'Dorking West',
	'Drayton Green',
	'Ealing Broadway station',
	'Eggesford',
	'Evesham',
	'Exeter Central',
	"Exeter St David's",
	'Exeter St Thomas',
	'Exmouth',
	'Exton',
	'Falmouth Docks',
	'Falmouth Town',
	'Filton Abbey Wood',
	'Finstock',
	'Freshford',
	'Frome',
	'Furze Platt',
	'Gloucester',
	'Gomshall',
	'Goring & Streatley',
	'Greenford station',
	'Gunnislake',
	'Hanborough',
	'Hayes & Harlington',
	'Hayle',
	'Henley-on-Thames',
	'Heyford',
	'Highbridge and Burnham',
	'Honeybourne',
	'Hungerford',
	'Iver',
	'Ivybridge',
	'Kemble',
	'Keyham',
	'Keynsham',
	'Kingham',
	'Kings Nympton',
	'Kintbury',
	'Lamphey',
	'Langley',
	'Lapford',
	'Lawrence Hill',
	'Lelant',
	'Lelant Saltings',
	'Liskeard',
	'Looe',
	'Lostwithiel',
	'Luxulyan',
	'Lympstone Commando',
	'Lympstone Village',
	'Maiden Newton',
	'Maidenhead',
	'Marlow',
	'Melksham',
	'Menheniot',
	'Midgham',
	'Montpelier',
	'Morchard Road',
	'Moreton-in-Marsh',
	'Mortimer',
	'Nailsea and Backwell',
	'Newbury Racecourse',
	'Newbury',
	'Newcourt',
	'Newquay',
	'Newton Abbot',
	'Newton St Cyres',
	'Okehampton',
	'Oldfield Park',
	'Oxford',
	'Paignton',
	'Pangbourne',
	'Par',
	'Parson Street',
	'Patchway',
	'Penmere',
	'Penryn',
	'Penzance',
	'Perranwell',
	'Pershore',
	'Pewsey',
	'Pilning',
	'Plymouth',
	'Polsloe Bridge',
	'Portsmouth Arms',
	'Quintrell Downs',
	'Radley',
	'Reading',
	'Reading West',
	'Redhill',
	'Redland',
	'Redruth',
	'Reigate',
	'Roche',
	'St Andrews Road',
	'St Austell',
	'St Budeaux Ferry Road',
	'St Budeaux Victoria Road',
	'St Columb Road',
	'St Erth',
	'St Germans',
	'St Ives',
	'St James Park',
	'St Keyne Wishing Well Halt',
	'Saltash',
]

export const HEATHROW_EXPRESS = [
	'Heathrow Airport Terminal 4',
	'Heathrow Airport Terminal 5',
	'Heathrow Airport Terminals 1, 2 and 3',
]

export const LNER = [
	'Berwick upon Tweed',
	'Newcastle',
	'Durham',
	'Darlington',
	'York',
	'Wakefield Westgate',
	'Doncaster',
	'Retford',
	'Newark Northgate',
	'Grantham',
	'Peterborough',
]

export const LONDON_NORTHWESTERN_RAILWAY = [
	'Acton Bridge (Cheshire)',
	'Alsager',
	'Apsley',
	'Aspley Guise',
	'Atherstone',
	'Bedford',
	'Bedford St Johns',
	'Berkhamsted',
	'Bletchley',
	'Bow Brickhill',
	'Bricket Wood',
	'Bushey',
	'Cheddington',
	'Fenny Stratford',
	'Garston (Hertfordshire)',
	'Harrow & Wealdstone',
	'Hartford (Cheshire)',
	'Hemel Hempstead',
	'How Wood (Hertfordshire)',
	'Kempston Hardwick',
	'Kidsgrove',
	'Kings Langley',
	'Leighton Buzzard',
	'Lidlington',
	'Long Buckby',
	'Millbrook (Bedfordshire)',
	'Milton Keynes Central',
	'Northampton',
	'Norton Bridge',
	'Nuneaton',
	'Park Street',
	'Penkridge',
	'Polesworth',
	'Ridgmont',
	'Rugby',
	'Runcorn',
	'St Albans Abbey',
	'Stafford',
	'Stechford',
	'Tamworth',
	'Tring',
	'Watford Junction',
	'Watford North',
	'Wedgwood',
	'Wembley Central',
	'Winsford',
	'Woburn Sands',
	'Wolverton',
]

export const MERSEYRAIL = [
	'Aigburth',
	'Ainsdale',
	'Aintree',
	'Bank Hall',
	'Bebington',
	'Bidston',
	'Birkdale',
	'Birkenhead Central',
	'Birkenhead Hamilton Square',
	'Birkenhead North',
	'Birkenhead Park',
	'Blundellsands & Crosby',
	'Bootle New Strand',
	'Bootle Oriel Road',
	'Broad Green',
	'Bromborough',
	'Bromborough Rake',
	'Brunswick',
	'Conway Park',
	'Cressington',
	'Earlestown',
	'Eastham Rake',
	'Eccleston Park',
	'Edge Hill',
	'Fazakerley',
	'Formby',
	'Freshfield',
	'Garswood',
	'Green Lane',
	'Halewood',
	'Hall Road',
	'Heswall',
	'Hightown',
	'Hillside',
	'Hoylake',
	'Hunts Cross',
	'Huyton',
	'Kirkby',
	'Kirkdale',
	'Lea Green',
	'Leasowe',
	'Liverpool Central',
	'Liverpool James Street',
	'Liverpool Lime Street',
	'Liverpool South Parkway',
	'Maghull',
	'Maghull North',
	'Manor Road',
	'Meols',
	'Meols Cop',
	'Moorfields',
	'Moreton',
	'Mossley Hill',
	'New Brighton',
	'Newton-le-Willows',
	'Old Roan',
	'Orrell Park',
	'Port Sunlight',
	'Prescot',
	'Rainford',
	'Rainhill',
	'Rice Lane',
	'Roby',
	'Rock Ferry',
	'Sandhills',
	'Seaforth & Litherland',
	'Southport',
	'Spital',
	'St Helens Central',
	'St Helens Junction',
	'St Michaels',
	'Thatto Heath',
	'Upton',
	'Wallasey Grove Road',
	'Wallasey Village',
	'Walton',
	'Waterloo',
	'Wavertree Technology Park',
	'West Allerton',
	'West Kirby',
	'Whiston',
]

export const NORTHERN = [
	'Accrington',
	'Acklington',
	'Adlington',
	'Adlington',
	'Adwick',
	'Alderley Edge',
	'Alfreton',
	'Allens West',
	'Alnmouth',
	'Althorpe',
	'Altrincham',
	'Ansdell & Fairhaven',
	'Apperley Bridge',
	'Appleby',
	'Appley Bridge',
	'Ardwick',
	'Armathwaite',
	'Arnside',
	'Arram',
	'Ashburys',
	'Ashley',
	'Ashton-under-Lyne',
	'Askam',
	'Aspatria',
	'Atherton',
	'Baildon',
	'Bamber Bridge',
	'Bamford',
	'Bardon Mill',
	'Bare Lane',
	'Barnetby',
	'Barnsley',
	'Barrow-in-Furness',
	'Batley',
	'Battersby',
	'Belle Vue',
	'Bempton',
	'Ben Rhydding',
	'Bentham',
	'Bentley',
	'Berry Brow',
	'Bescar Lane',
	'Beverley',
	'Billingham',
	'Bingley',
	'Bishop Auckland',
	'Blackburn',
	'Blackpool North',
	'Blackpool Pleasure Beach',
	'Blackpool South',
	'Blackrod',
	'Blaydon',
	'Bolton',
	'Bolton-upon-Dearne',
	'Bootle',
	'Bradford Forster Square',
	'Bradford Interchange',
	'Bramhall',
	'Bramley',
	'Brampton',
	'Braystones',
	'Bredbury',
	'Bridlington',
	'Brierfield',
	'Brigg',
	'Brighouse',
	'Brinnington',
	'Broad Green',
	'Broadbottom',
	'Brockholes',
	'Bromley Cross',
	'Broomfleet',
	'Brough',
	'Bryn',
	'Buckshaw Parkway',
	'Burley Park',
	'Burley-in-Wharfedale',
	'Burnage',
	'Burneside',
	'Burnley Barracks',
	'Burnley Central',
	'Burnley Manchester Road',
	'Burscough Bridge',
	'Burscough Junction',
	'Buxton',
	'Cark & Cartmel',
	'Carlisle',
	'Carnforth',
	'Castleford',
	'Castleton',
	'Castleton Moor',
	'Cattal',
	'Chapel-en-le-Frith',
	'Chapeltown',
	'Chassen Road',
	'Chathill',
	'Cheadle Hulme',
	'Chelford',
	'Cherry Tree',
	'Chester',
	'Chester-le-Street',
	'Chesterfield',
	'Chinley',
	'Chorley',
	'Church & Oswaldtwistle',
	'Church Fenton',
	'Clapham',
	'Cleethorpes',
	'Clifton',
	'Clitheroe',
	'Colne',
	'Commondale',
	'Congleton',
	'Conisbrough',
	'Cononley',
	'Corbridge',
	'Corkickle',
	'Cottingham',
	'Cottingley',
	'Cramlington',
	'Cross Gates',
	'Crossflatts',
	'Croston',
	'Crowle',
	'Cuddington',
	'Daisy Hill',
	'Dalston',
	'Dalton',
	'Danby',
	'Darnall',
	'Darton',
	'Darwen',
	'Davenport',
	'Deansgate',
	'Deighton',
	'Delamere',
	'Denby Dale',
	'Dent',
	'Denton',
	'Dewsbury',
	'Dinsdale',
	'Dinting',
	'Disley',
	'Dodworth',
	'Dore & Totley',
	'Dove Holes',
	'Driffield',
	'Drigg',
	'Dronfield',
	'Dunston',
	'Eaglescliffe',
	'Earlestown',
	'East Didsbury',
	'East Garforth',
	'Eastrington',
	'Eccles',
	'Eccleston Park',
	'Edale',
	'Edge Hill',
	'Egton',
	'Ellesmere Port',
	'Elsecar',
	'Entwistle',
	'Euxton Balshaw Lane',
	'Fairfield',
	'Farnworth',
	'Featherstone',
	'Ferriby',
	'Filey',
	'Fitzwilliam',
	'Flimby',
	'Flixton',
	'Flowery Field',
	'Foxfield',
	'Frizinghall',
	'Frodsham',
	'Furness Vale',
	'Gainsborough Central',
	'Gainsborough Lea Road',
	'Garforth',
	'Gargrave',
	'Garsdale',
	'Garswood',
	'Gathurst',
	'Gatley',
	'Giggleswick',
	'Gilberdyke',
	'Glaisdale',
	'Glasshoughton',
	'Glazebrook',
	'Glossop',
	'Godley',
	'Goldthorpe',
	'Goole',
	'Goostrey',
	'Gorton',
	'Grange-over-Sands',
	'Great Ayton',
	'Green Road',
	'Greenbank',
	'Greenfield',
	'Grimsby Town',
	'Grindleford',
	'Grosmont',
	'Guide Bridge',
	'Guiseley',
	'Gypsy Lane',
	'Habrough',
	'Hadfield',
	'Hag Fold',
	'Hale',
	'Halewood',
	'Halifax',
	"Hall-i'-th'-Wood",
	'Haltwhistle',
	'Hammerton',
	'Handforth',
	'Hapton',
	'Harrington',
	'Harrogate',
	'Hartlepool',
	'Hatfield & Stainforth',
	'Hathersage',
	'Hattersley',
	'Haydon Bridge',
	'Hazel Grove',
	'Headingley',
	'Heald Green',
	'Heaton Chapel',
	'Hebden Bridge',
	'Heighington',
	'Hellifield',
	'Hensall',
	'Hessle',
	'Heworth',
	'Hexham',
	'Heysham Port',
	'Hindley',
	'Holmes Chapel',
	'Honley',
	'Hope',
	'Horden',
	'Hornbeam Park',
	'Horsforth',
	'Horton-in-Ribblesdale',
	'Hoscar',
	'Hough Green',
	'Howden',
	'Humphrey Park',
	'Huncoat',
	'Hunmanby',
	'Hutton Cranswick',
	'Huyton',
	'Hyde Central',
	'Hyde North',
	'Ilkley',
	'Ince & Elton',
	'Ince',
	'Irlam',
	'James Cook University Hospital',
	'Kearsley',
	'Keighley',
	'Kendal',
	'Kents Bank',
	'Kidsgrove',
	'Kildale',
	'Kirk Sandall',
	'Kirkby',
	'Kirkby Stephen',
	'Kirkby-in-Furness',
	'Kirkham & Wesham',
	'Kirkstall Forge',
	'Kirton Lindsey',
	'Kiveton Bridge',
	'Kiveton Park',
	'Knaresborough',
	'Knottingley',
	'Knutsford',
	'Langho',
	'Langley Mill',
	'Langwathby',
	'Layton',
	'Lazonby & Kirkoswald',
	'Lealholm',
	'Levenshulme',
	'Leyland',
	'Littleborough',
	'Lockwood',
	'Long Preston',
	'Longbeck',
	'Lostock',
	'Lostock Gralam',
	'Lostock Hall',
	'Low Moor',
	'Lytham',
	'Manchester Victoria',
	'Manors',
	'Marple',
	'Marsden',
	'Marske',
	'Marton',
	'Maryport',
	'Mauldeth Road',
	'Meadowhall',
	'Menston',
	'Meols Cop',
	'MetroCentre',
	'Mexborough',
	'Micklefield',
	'Middlesbrough',
	'Middlewood',
	'Mill Hill',
	'Millom',
	'Mills Hill',
	'Mirfield',
	'Mobberley',
	'Moorside',
	'Moorthorpe',
	'Morecambe',
	'Morley',
	'Morpeth',
	'Moses Gate',
	'Moss Side',
	'Mossley',
	'Mossley Hill',
	'Moston',
	'Mouldsworth',
	'Mytholmroyd',
	'Nafferton',
	'Navigation Road',
	'Nelson',
	'Nethertown',
	'New Lane',
	'New Mills Central',
	'New Mills Newtown',
	'New Pudsey',
	'Newcastle',
	'Newton Aycliffe',
	'Newton for Hyde',
	'Normanton',
	'North Road',
	'Northwich',
	'Nottingham',
	'Nunthorpe',
	'Orrell',
	'Outwood',
	'Padgate',
	'Pannal',
	'Parbold',
	'Parton',
	'Patricroft',
	'Pegswood',
	'Pemberton',
	'Penistone',
	'Pleasington',
	'Plumley',
	'Pontefract Baghill',
	'Pontefract Monkhill',
	'Pontefract Tanshelf',
	'Poppleton',
	'Poulton-le-Fylde',
	'Poynton',
	'Prescot',
	'Prestbury',
	'Preston',
	'Prudhoe',
	'Rainford',
	'Rainhill',
	'Ramsgreave & Wilpshire',
	'Ravenglass for Eskdale',
	'Ravensthorpe',
	'Rawcliffe',
	'Redcar British Steel',
	'Redcar Central',
	'Redcar East',
	'Reddish North',
	'Reddish South',
	'Retford',
	'Ribblehead',
	'Riding Mill',
	'Rishton',
	'Roby',
	'Rochdale',
	'Romiley',
	'Roose',
	'Rose Grove',
	'Rose Hill Marple',
	'Rotherham Central',
	'Rufford',
	'Runcorn East',
	'Ruswarp',
	'Ryder Brow',
	'Salford Central',
	'Salford Crescent',
	'Saltaire',
	'Saltburn',
	'Saltmarshe',
	'Salwick',
	'Sandal & Agbrigg',
	'Sandbach',
	'Sankey for Penketh',
	'Saxilby',
	'Scarborough',
	'Scunthorpe',
	'Seaham',
	'Seamer',
	'Seascale',
	'Seaton Carew',
	'Selby',
	'Sellafield',
	'Settle',
	'Shepley',
	'Sherburn-in-Elmet',
	'Shildon',
	'Shipley',
	'Shireoaks',
	'Silecroft',
	'Silkstone Common',
	'Silverdale',
	'Skipton',
	'Slaithwaite',
	'Sleights',
	'Smithy Bridge',
	'Snaith',
	'South Bank',
	'South Elmsall',
	'South Milford',
	'Southport',
	'Sowerby Bridge',
	'Squires Gate',
	'St Annes-on-the-Sea',
	'St Bees',
	'St Helens Central',
	'St Helens Junction',
	'Stalybridge',
	'Stanlow & Thornton',
	'Starbeck',
	'Staveley',
	'Steeton & Silsden',
	'Stockport',
	'Stocksfield',
	'Stocksmoor',
	'Stockton',
	'Streethouse',
	'Strines',
	'Styal',
	'Sunderland',
	'Swinton',
	'Swinton',
	'Teesside Airport',
	'Thatto Heath',
	'Thornaby',
	'Thorne North',
	'Thorne South',
	'Thurnscoe',
	'Todmorden',
	'Trafford Park',
	'Ulleskelf',
	'Ulverston',
	'Upholland',
	'Urmston',
	'Wakefield Kirkgate',
	'Walkden',
	'Walsden',
	'Warrington West',
	'Wavertree Technology Park',
	'Weeton',
	'Wennington',
	'West Allerton',
	'Westhoughton',
	'Wetheral',
	'Whaley Bridge',
	'Whalley',
	'Whiston',
	'Whitby',
	'Whitehaven',
	'Whitley Bridge',
	'Widdrington',
	'Widnes',
	'Wigan Wallgate',
	'Wigton',
	'Wilmslow',
	'Windermere',
	'Wombwell',
	'Woodhouse',
	'Woodlesford',
	'Woodley',
	'Woodsmoor',
	'Workington',
	'Worksop',
	'Wressle',
	'Wylam',
]

export const SCOTRAIL = [
	'Aberdeen',
	'Aberdour',
	'Ardgay',
	'Ardlui',
	'Arisaig',
	'Aviemore',
	'Ayr',
	"Bo'ness",
	'Boat of Garten',
	'Bridge of Orchy',
	'Bridge Street',
	'Bridgeton Central',
	'Brora',
	'Broughty Ferry',
	'Cardross',
	'Carrbridge',
	'Coatbridge Sunnyside',
	'Corrour',
	'Crookston',
	'Cumberland Street',
	'Cupar',
	'Dalmally',
	'Dingwall',
	'Dumbarton Central',
	'Dumfries',
	'Dunbar',
	'Dunblane',
	'Duncraig',
	'Dunrobin Castle',
	'Edinburgh Waverley',
	'Fearn',
	'Fort Matilda',
	'Garelochhead',
	'Glasgow Central',
	'Glasgow Queen Street',
	'Glenfinnan',
	'Golspie',
	'Haymarket',
	'Helensburgh Central',
	'Helmsdale',
	'Inverurie',
	'Irvine',
	'Kilmarnock',
	'Kingussie',
	'Kyle of Lochalsh',
	'Ladybank',
	'Laurencekirk',
	'Linlithgow',
	'Lochee',
	'Longforgan',
	'Markinch',
	'Maxwell Park',
	'Milngavie',
	'Muirend',
	'Nairn',
	'Newtonmore',
	'Paisley Gilmour Street',
	'Perth',
	'Plockton',
	'Pollokshaws West',
	'Possil',
	'Rannoch',
	'St Leonards',
	'Spean Bridge',
	'Springburn',
	'Stirling',
	'Stonehaven',
	'Strathpeffer',
	'Tain',
	'Thurso',
	'Troon',
	'Wemyss Bay',
	'West Calder',
	'West Kilbride',
	'Whitecraigs',
	'Wick',
]

export const SOUTHEASTERN = [
	'Bat & Ball',
	'Bickley',
	'Charlton',
	'Dartford',
	'Deptford',
	'Eynsford',
	'Gravesend',
	'Greenwich',
	'Higham',
	'Maze Hill',
	'Orpington',
	'Otford',
	'Petts Wood',
	'Rainham (Kent)',
	'Sevenoaks',
	'Shoreham (Kent)',
	'Shortlands',
	'Slade Green',
	'Stone',
	'Strood',
	'Swanley',
	'Swanscombe',
	'Westcombe',
	'Woolwich Arsenal',
]

export const SOUTH_WESTERN_RAILWAY = [
	'Addlestone',
	'Aldershot',
	'Alton',
	'Andover',
	'Ascot',
	'Ash',
	'Ash Vale',
	'Ashford Middlesex',
	'Ashtead',
	'Ashurst New Forest',
	'Axminster',
	'Bagshot',
	'Barnes',
	'Barnes Bridge',
	'Basingstoke',
	'Beaulieu Road',
	'Bedhampton',
	'Bentley',
	'Berrylands',
	'Bitterne',
	'Bookham',
	'Botley',
	'Bournemouth',
	'Box Hill and Westhumble',
	'Bracknell',
	'Brading',
	'Branksome',
	'Brentford',
	'Brockenhurst',
	'Brookwood',
	'Bruton',
	'Bursledon',
	'Byfleet and New Haw',
	'Camberley',
	'Chandlers Ford',
	'Chertsey',
	'Chessington North',
	'Chessington South',
	'Chiswick',
	'Christchurch',
	'Clandon',
	'Claygate',
	"Cobham and Stoke d'Abernon",
	'Corfe Castle',
	'Cosham',
	'Cranbrook Devon',
	'Crewkerne Datchet',
	'Dean (Wilts)',
	'Dorchester South',
	'Dorking (Main)',
	'Earley',
	'Earlsfield',
	'Eastleigh',
	'Effingham Junction',
	'Egham',
	'Epsom Surrey',
	'Esher',
	'Ewell West',
	'Fareham',
	'Farnborough (Main)',
	'Farncombe',
	'Farnham',
	'Feltham',
	'Feniton',
	'Fleet',
	'Fratton',
	'Frimley',
	'Fulwell',
	'Gillingham (Dorset)',
	'Godalming',
	'Grateley',
	'GuildfordHamble',
	'Hampton London',
	'Hampton Court',
	'Hampton Wick',
	'Hamworthy',
	'Haslemere',
	'Havant',
	'Hedge End',
	'Hersham',
	'Hilsea',
	'Hinchley Wood',
	'Hinton Admiral',
	'Holton Heath',
	'Honiton',
	'Hook',
	'Horsley',
	'Hounslow',
	'Isleworth',
	'Kempton Park Racecourse',
	'Kew Bridge',
	'Kingston',
	'Lake',
	'Leatherhead',
	'Liphook',
	'Liss',
	'London Road (Guildford)',
	'Longcross',
	'Lymington Pier',
	'Lymington Town',
	'Malden Manor',
	'Martins Heron',
	'Micheldever',
	'Milford (Surrey)',
	'Millbrook (Hants)',
	'Moreton (Dorset)',
	'Mortlake',
	'Motspur Park',
	'Mottisfont and Dunbridge',
	'Netley',
	'New Malden',
	'New Milton',
	'Norbiton',
	'North Sheen',
	'Overton',
	'Oxshott',
	'Parkstone Dorset',
	'Petersfield',
	'Pinhoe',
	'Pokesdown',
	'Poole',
	'Portchester',
	'Portsmouth and Southsea',
	'Portsmouth Harbour',
	'Putney',
	'Queenstown Road (Battersea)',
	'Raynes Park',
	'Reading',
	'Redbridge',
	'Richmond (London)',
	'Romsey',
	'Rowlands Castle',
	'Ryde Esplanade',
	'Ryde Pier Head',
	'Ryde St Johns Road',
	'Salisbury',
	'Sandown',
	'Shanklin',
	'Shawford',
	'Shepperton',
	'Sherborne',
	'Sholing',
	'Smallbrook Junction',
	'Southampton Airport Parkway',
	'Southampton Central',
	'Staines',
	'St Denys',
	'St Margarets (London)',
	'Stoneleigh',
	'Strawberry Hill',
	'Sunbury',
	'Sunningdale',
	'Sunnymeads',
	'Surbiton',
	'Swanwick',
	'Sway',
	'Swaythling',
	'Syon Lane',
	'Teddington',
	'Templecombe',
	'Thames Ditton',
	'Tisbury',
	'Tolworth',
	'Totton',
	'Trowbridge',
	'Twickenham',
	'Upper Halliford',
	'Upwey',
	'Vauxhall',
	'Virginia Water',
	'Walton-On-Thames',
	'Wanborough',
	'Wandsworth Town',
	'Wareham (Dorset)',
	'Warminster',
	'West Byfleet',
	'Westbury',
	'Weybridge',
	'Weymouth',
	'Whimple',
	'Whitchurch (Hampshire)',
	'Whitton (London)',
	'Wimbledon',
	'Winchester',
	'Winchfield',
	'Windsor and Eton Riverside',
	'Winnersh',
	'Winnersh Triangle',
	'Witley',
	'Woking',
	'Wokingham',
	'Wool',
	'Woolston',
	'Worcester Park',
	'Worplesdon',
	'Wraysbury',
	'Yeovil Junction',
]

export const TFL_RAIL = [
	'Acton Main Line',
	'Brentwood',
	'Burnham (Berks)',
	'Chadwell Heath',
	'Ealing Broadway',
	'Forest Gate',
	'Gidea Park',
	'Goodmayes',
	'Hanwell',
	'Harold Wood',
	'Hayes & Harlington',
	'Heathrow Terminal 5',
	'Heathrow Terminals 2 & 3',
	'Ilford',
	'Iver',
	'Langley (Berks)',
	'London Liverpool Street',
	'Maidenhead',
	'Manor Park',
	'Maryland',
	'Reading',
	'Romford',
	'Seven Kings',
	'Shenfield',
	'Slough',
	'Southall',
	'Stratford (London)',
	'Taplow',
	'Twyford',
	'West Drayton',
	'West Ealing',
]

export const THAMESLINK = [
	'Abbey Wood',
	'Aldrington',
	'Alexandra Palace',
	'Amberley',
	'Anerley',
	'Angmering',
	'Appledore',
	'Arlesey',
	'Arundel',
	'Ashford International',
	'Ashtead',
	'Ashurst',
	'Ashwell & Morden',
	'Balcombe',
	'Baldock',
	'Balham',
	'Bat & Ball',
	'Banstead',
	'Barnham',
	'Battersea Park',
	'Bayford',
	'Beckenham Junction',
	'Beckenham Hill',
	'Bedford',
	'Bedhampton',
	'Bellingham',
	'Belmont',
	'Berkhamsted',
	'Berwick (Sussex)',
	'Bexhill',
	'Bickley',
	'Biggleswade',
	'Billingshurst',
	'Birkbeck',
	'Bishopstone (Sussex)',
	'Bitterne',
	'Bletchley',
	'Bognor Regis',
	'Bookham',
	'Bosham',
	'Bowes Park',
	'Box Hill & Westhumble',
	'Brighton (East Sussex)',
	'Brockley',
	'Bromley South',
	'Brookmans Park',
	'Burgess Hill',
	'Bursledon',
	'Buxted',
	'Cooden Beach',
	'Carshalton Beeches',
	'Cambridge',
	'Cambridge North',
	'Carshalton',
	'Caterham',
	'Catford',
	'Charlton',
	'Chatham',
	'Cheam',
	'Chichester',
	'Chipstead',
	'Christs Hospital',
	'City Thameslink',
	'Clandon',
	'Clapham Junction',
	'Collington',
	'Cooksbridge',
	'Cosham',
	'Coulsdon South',
	'Coulsdon Town',
	'Cowden (Kent)',
	'Crawley',
	'Crews Hill',
	'Cricklewood',
	'Crofton Park',
	'Crowborough',
	'Crystal Palace',
	'Cuffley',
	'Dartford',
	'Denmark Hill',
	'Deptford',
	'Doleham',
	'Dorking (Main)',
	'Dormans',
	'Downham Market',
	'Drayton Park',
	'Durrington-on-Sea',
	'Elstree & Borehamwood',
	'Elephant & Castle',
	'Enfield Chase',
	'East Croydon',
	'Epsom Downs',
	'East Dulwich',
	'Earlswood (Surrey)',
	'East Grinstead',
	'East Worthing',
	'Ewell East',
	'Eastbourne',
	'Eastleigh',
	'Edenbridge Town',
	'Edenbridge',
	'Effingham Junction',
	'Ely',
	'Emsworth',
	'Epsom (Surrey)',
	'Eridge',
	'Essex Road',
	'Eynsford',
	'Falmer',
	'Fareham',
	'Farringdon',
	'Faygate',
	'Finsbury Park',
	'Fishbourne (Sussex)',
	'Fishersgate',
	'Flitwick',
	'Ford',
	'Forest Hill',
	'Foxton',
	'Fratton',
	'Gatwick Airport',
	'Goring-by-Sea',
	'Gillingham (Kent)',
	'Gipsy Hill',
	'Glynde',
	'Godstone',
	'Gordon Hill',
	'Grange Park',
	'Gravesend',
	'Greenhithe',
	'Greenwich',
	'Guildford',
	'Harlington (Beds)',
	'Hurst Green',
	'Hackbridge',
	'Hadley Wood',
	'Ham Street',
	'Hamble',
	'Hampden Park (Sussex)',
	'Harpenden',
	'Harringay',
	'Harrow & Wealdstone',
	'Hassocks',
	'Hastings',
	'Hatfield (Herts)',
	'Havant',
	'Haydons Road',
	'Haywards Heath',
	'Hemel Hempstead',
	'Hendon',
	'Herne Hill',
	'Hertford North',
	'Hever',
	'Higham (Kent)',
	'Highbury & Islington',
	'Hilsea',
	'Hitchin',
	'Holmwood',
	'Honor Oak Park',
	'Horley',
	'Hornsey',
	'Horsham',
	'Horsley',
	'Hove',
	'Huntingdon',
	'Ifield',
	'Imperial Wharf',
	'Kenley',
	'Kensington Olympia',
	'Kentish Town',
	'Kings Lynn',
	'Kingswood',
	'Knebworth',
	'Luton Airport Parkway',
	'London Blackfriars',
	'London Bridge',
	'London Road (Brighton)',
	'Leighton Buzzard',
	'Letchworth Garden City',
	'London Kings Cross',
	'London Road (Guildford)',
	'London St Pancras International',
	'Loughborough Junction',
	'Leigh (Kent)',
	'Lancing',
	'Leagrave',
	'Leatherhead',
	'Lewes',
	'Lingfield',
	'Littlehampton',
	'Littlehaven',
	'Littleport',
	'Luton',
	'Mill Hill Broadway',
	'Milton Keynes Central',
	'Mitcham Eastfields',
	'Maze Hill',
	'Mitcham Junction',
	'Meldreth',
	'Merstham',
	'Moorgate',
	'Morden South',
	'Moulsecoomb',
	'New Barnet',
	'Normans Bay',
	'New Cross Gate',
	'North Dulwich',
	'Newhaven Harbour',
	'Norwood Junction',
	'Netley',
	'New Southgate',
	'Newhaven Town',
	'Norbury',
	'Northfleet',
	'Nunhead',
	'Nutbourne',
	'Nutfield',
	'Oakleigh Park',
	'Ockley',
	'Old Street',
	'Ore',
	'Orpington',
	'Otford',
	'Oxted',
	'Potters Bar',
	'Pevensey Bay',
	'Palmers Green',
	'Portsmouth Harbour',
	'Purley Oaks',
	'Preston Park',
	'Peckham Rye',
	'Penge West',
	'Penshurst',
	'Peterborough',
	'Petts Wood',
	'Pevensey & Westham',
	'Plumpton',
	'Plumstead',
	'Polegate',
	'Portchester',
	'Portslade',
	'Portsmouth & Southsea',
	'Pulborough',
	'Purley',
	'Queens Road (Peckham)',
	'Rainham (Kent)',
	'Radlett',
	'Ravensbourne',
	'Redhill',
	'Reedham (Surrey)',
	'Reigate',
	'Riddlesdown',
	'Rochester',
	'Royston',
	'Rye (Sussex)',
	'Southampton Airport Parkway',
	'St Albans City',
	'South Bermondsey',
	"Shepherd's Bush",
	'Shoreham-by-Sea',
	'Southampton Central',
	'Streatham Common',
	'Sutton Common',
	'St Mary Cray',
	'Stone Crossing',
	'South Croydon',
	'St Denys',
	'Streatham (Greater London)',
	'Slade Green',
	'St Helier (Surrey)',
	'Streatham Hill',
	'Shoreham (Kent)',
	'Strood (Kent)',
	'St Leonards Warrior Square',
	'Sydenham (London)',
	'South Merton',
	'St Neots',
	'Salfords (Surrey)',
	'Sanderstead',
	'Sandy',
	'Seaford (Sussex)',
	'Selhurst',
	'Sevenoaks',
	'Shepreth',
	'Sholing',
	'Shortlands',
	'Southbourne',
	'Southease',
	'Southwick',
	'Stevenage',
	'Sutton (Surrey)',
	'Swanley',
	'Swanscombe',
	'Swanwick',
	'Three Bridges',
	'Tattenham Corner',
	'Thornton Heath',
	'Tulse Hill',
	'Three Oaks',
	'Tadworth',
	'Tooting',
	'Tring',
	'Uckfield',
	'Upper Warlingham',
	'Woolwich Arsenal',
	'Watton-at-Stone',
	'West Brompton',
	'Wembley Central',
	'Wimbledon Chase',
	'Welwyn Garden City',
	'Wandsworth Common',
	'Welham Green',
	'West Hampstead Thameslink',
	'Winchmore Hill',
	'Watford Junction',
	'Welwyn North',
	'West Norwood',
	'Westcombe Park',
	'Whyteleafe South',
	'West Sutton',
	'Waddon',
	'Wallington',
	'Warblington',
	'Warnham',
	'Waterbeach',
	'Watlington',
	'West Worthing',
	'Whyteleafe',
	'Wimbledon',
	'Winchelsea',
	'Wivelsfield',
	'Woldingham',
	'Woodmansterne',
	'Woolston',
	'Worthing',
]

export const TRANSPENNINE_EXPRESS = [
	'Barnetby',
	'Brough',
	'Cleethorpes',
	'Dewsbury',
	'Grimsby Town',
	'Huddersfield',
	'Hull Paragon',
	'Malton',
	'Manchester Airport',
	'Middlesbrough',
	'Northallerton',
	'Scarborough',
	'Scunthorpe',
	'Seamer',
	'Selby',
	'Stalybridge',
	'Thirsk',
	'Thornaby',
	'Yarm',
]

export const TRANSPORT_FOR_WALES = [
	'Aber',
	'Abercynon',
	'Aberdare',
	'Aberdovey',
	'Abererch',
	'Abergavenny',
	'Abergele & Pensarn',
	'Aberystwyth',
	'Ammanford',
	'Baglan',
	'Bangor (Gwynedd)',
	'Bargoed',
	'Barmouth',
	'Barry',
	'Barry Docks',
	'Barry Island',
	'Betws-y-Coed',
	'Birchgrove',
	'Blaenau Ffestiniog',
	'Bodorgan',
	'Borth',
	'Bow Street',
	'Bridgend',
	'Brithdir',
	'Briton Ferry',
	'Broome',
	'Buckley',
	'Bucknell',
	'Builth Road',
	'Bynea',
	'Cadoxton',
	'Caergwrle',
	'Caerphilly',
	'Caersws',
	'Caldicot',
	'Cardiff Bay',
	'Cardiff Central',
	'Cardiff Queen Street',
	'Carmarthen',
	'Cathays',
	'Cefn-y-Bedd',
	'Chepstow',
	'Chester',
	'Chirk',
	'Church Stretton',
	'Cilmeri',
	'Clarbeston Road',
	'Clunderwen',
	'Cogan',
	'Colwyn Bay',
	'Conwy',
	'Coryton',
	'Craven Arms',
	'Criccieth',
	'Crosskeys',
	'Cwmbach',
	'Cwmbran',
	'Cynghordy',
	'Danescourt',
	'Deganwy',
	'Dinas (Rhondda)',
	'Dinas Powys',
	'Dingle Road',
	'Dolau',
	'Dolgarrog',
	'Dolwyddelan',
	'Dovey Junction',
	'Dyffryn Ardudwy',
	'Eastbrook',
	'Ebbw Vale Parkway',
	'Ebbw Vale Town',
	'Energlyn & Churchill Park',
	'Fairbourne',
	'Fairwater',
	'Fernhill',
	'Ferryside',
	'Ffairfach',
	'Fishguard & Goodwick',
	'Fishguard Harbour',
	'Flint',
	'Frodsham',
	'Garth (Bridgend County)',
	'Garth (Powys)',
	'Gilfach Fargoed',
	'Glan Conwy',
	'Gobowen',
	'Gowerton',
	'Grangetown (Cardiff)',
	'Gwersyllt',
	'Harlech',
	'Haverfordwest',
	'Hawarden',
	'Hawarden Bridge',
	'Heath High Level',
	'Heath Low Level',
	'Helsby',
	'Hengoed',
	'Hereford',
	'Heswall',
	'Holyhead',
	'Hope (Flintshire)',
	'Hopton Heath',
	'Johnston',
	'Kidwelly',
	'Kilgetty',
	'Knighton',
	'Knucklas',
	'Lamphey',
	'Leominster',
	'Lisvane & Thornhill',
	'Llanaber',
	'Llanbedr',
	'Llanbister Road',
	'Llanbradach',
	'Llandaf',
	'Llandanwg',
	'Llandecwyn',
	'Llandeilo',
	'Llandovery',
	'Llandrindod',
	'Llandudno',
	'Llandudno Junction',
	'Llandybie',
	'Llanelli',
	'Llanfairfechan',
	'Llanfairpwll',
	'Llangadog',
	'Llangammarch',
	'Llangennech',
	'Llangynllo',
	'Llanharan',
	'Llanhilleth',
	'Llanishen',
	'Llanrwst',
	'Llansamlet',
	'Llantwit Major',
	'Llanwrda',
	'Llanwrtyd',
	'Llwyngwril',
	'Llwynypia',
	'Ludlow',
	'Lydney',
	'Machynlleth',
	'Maesteg',
	'Maesteg (Ewenny Road)',
	'Manorbier',
	'Merthyr Tydfil',
	'Merthyr Vale',
	'Milford Haven',
	'Minffordd',
	'Morfa Mawddach',
	'Mountain Ash',
	'Nantwich',
	'Narberth',
	'Neath',
	'Neston',
	'Newbridge',
	'Newport (South Wales)',
	'Newtown (Powys)',
	'Ninian Park',
	'North Llanrwst',
	'Pantyffynnon',
	'Pembrey & Burry Port',
	'Pembroke',
	'Pembroke Dock',
	'Pen-y-Bont (Mid Wales)',
	'Penally',
	'Penarth',
	'Pencoed',
	'Pengam',
	'Penhelig',
	'Penmaenmawr',
	'Penrhiwceiber',
	'Penrhyndeudraeth',
	'Pensarn (Gwynedd)',
	'Pentre-Bach',
	'Penychain',
	'Penyffordd',
	'Pont-y-Pant',
	'Pontarddulais',
	'Pontlottyn',
	'Pontyclun',
	'Pontypool & New Inn',
	'Pontypridd',
	'Port Talbot Parkway',
	'Porth',
	'Porthmadog',
	'Prees',
	'Prestatyn',
	'Pwllheli',
	'Pye Corner',
	'Pyle',
	'Quakers Yard',
	'Radyr',
	'Rhiwbina',
	'Rhoose Cardiff International Airport',
	'Rhosneigr',
	'Rhyl',
	'Rhymney',
	'Risca & Pontymister',
	'Rogerstone',
	'Roman Bridge',
	'Ruabon',
	'Runcorn East',
	'Sarn',
	'Saundersfoot',
	'Severn Tunnel Junction',
	'Shotton',
	'Shrewsbury',
	'Skewen',
	'Sugar Loaf',
	'Swansea',
	'Taffs Well',
	'Tal-y-Cafn',
	'Talsarnau',
	'Talybont',
	'Tenby',
	'Tir-Phil',
	'Ton Pentre',
	'Tondu',
	'Tonfanau',
	'Tonypandy',
	'Trefforest',
	'Trefforest Estate',
	'Trehafod',
	'Treherbert',
	'Treorchy',
	'Troed-y-rhiw',
	'Ty Croes',
	'Ty Glas',
	'Tygwyn',
	'Tywyn',
	'Upton',
	'Valley',
	'Waun-Gron Park',
	'Welshpool',
	'Wem',
	'Whitchurch (Cardiff)',
	'Whitchurch (Shropshire)',
	'Whitland',
	'Wildmill',
	'Wrenbury',
	'Wrexham Central',
	'Wrexham General',
	'Ynyswen',
	'Yorton',
	'Ystrad Mynach',
	'Ystrad Rhondda',
]

export const WEST_MIDLANDS_RAILWAY = [
	'Acocks Green',
	'Adderley Park',
	'Albrighton',
	'Alvechurch',
	'Aston',
	'Barlaston',
	'Barnt Green',
	'Bearley',
	'Berkswell',
	'Bermuda Park',
	'Bescot Stadium',
	'Bilbrook',
	'Birmingham Snow Hill',
	'Blake Street',
	'Blakedown',
	'Bloxwich',
	'Bloxwich North',
	'Bordesley',
	'Bournville',
	'Bromsgrove',
	'Butlers Lane',
	'Canley',
	'Cannock',
	'Chester Road',
	'Claverdon',
	'Codsall',
	'Coleshill Parkway',
	'Colwall',
	'Coseley',
	'Cosford',
	'Coventry',
	'Coventry Arena',
	'Cradley Heath',
	'Danzey',
	'Droitwich Spa',
	'Duddeston',
	'Dudley Port',
	'Earlswood (West Midlands)',
	'Erdington',
	'Five Ways',
	'Four Oaks',
	'Glasgow Central',
	'Gravelly Hill',
	'Great Malvern',
	'Hagley',
	'Hall Green',
	'Hampton-in-Arden',
	'Hamstead (Birmingham)',
	'Hartlebury',
	'Hatton',
	'Hednesford',
	'Henley-in-Arden',
	'Hereford',
	'Jewellery Quarter',
	'Kenilworth',
	'Kidderminster',
	'Kings Norton',
	'Landywood',
	'Langley Green',
	'Lapworth',
	'Lea Hall',
	'Leamington Spa',
	'Ledbury',
	'Lichfield City',
	'Lichfield Trent Valley',
	'Longbridge',
	'Lye (West Midlands)',
	'Malvern Link',
	'Marston Green',
	'Northfield',
	'Oakengates',
	'Old Hill',
	'Olton',
	'Perry Barr',
	'Redditch',
	'Rowley Regis',
	'Rugeley Town',
	'Rugeley Trent Valley',
	'Sandwell & Dudley',
	'Selly Oak',
	'Shenstone',
	'Shifnal',
	'Shirley',
	'Shrewsbury',
	'Small Heath',
	'Smethwick Galton Bridge',
	'Smethwick Rolfe Street',
	'Solihull',
	'Spring Road',
	'Stafford',
	'Stechford',
	'Stone (Staffs)',
	'Stourbridge Junction',
	'Stourbridge Town',
	'Stratford-upon-Avon',
	'Stratford-upon-Avon Parkway',
	'Sutton Coldfield',
	'Tame Bridge Parkway',
	'Telford Central',
	'The Hawthorns',
	'The Lakes (Warks)',
	'Tile Hill',
	'Tipton',
	'Tyseley',
	'University (Birmingham)',
	'Walsall',
	'Water Orton',
	'Wellington (Shropshire)',
	'Whitlocks End',
	'Widney Manor',
	'Wigan North Western',
	'Wilmcote',
	'Wilmslow',
	'Wilnecote (Staffs)',
	'Witton (West Midlands)',
	'Wood End',
	'Wootton Wawen',
	'Wolverhampton',
	'Worcester Foregate Street',
	'Worcester Shrub Hill',
	'Wylde Green',
	'Wythall',
	'Yardley Wood',
]
