export const CARRIAGES = [
	{ from: 'Ayr', to: 'Girvan', carriages: 2 },
	{ from: 'Ayr', to: 'Stranraer', carriages: 2 },
	{ from: 'Carlisle', to: 'Dumfries', carriages: 2 },
	{ from: 'Wrexham Central', to: 'Bidston', carriages: 3 },
	{ from: 'York', to: 'Hull', carriages: 2 },
	{ from: 'Inverurie', to: 'Montrose', carriages: 2 },
	{ from: 'Inverurie', to: 'Aberdeen', carriages: 2 },
	{ from: 'Dyce', to: 'Aberdeen', carriages: 2 },
	{ from: 'Elgin', to: 'Inverness', carriages: 2 },
	{ from: 'Arbroath', to: 'Edinburgh', carriages: 3 },
	{ from: 'London Euston', to: 'Blackpool North', carriages: 11 },
	{ from: 'London Liverpool Street', to: 'Norwich', carriages: 12 },
	{ from: 'Par', to: 'Newquay', carriages: 2 },
	{ from: 'Liskeard', to: 'Looe', carriages: 2 },
	{ from: 'Truro', to: 'Falmouth Docks', carriages: 2 },
	{ from: 'Morecambe', to: 'Lancaster', carriages: 2 },
	{ from: 'Southport', to: 'Alderley Edge', carriages: 4 },
	{ from: 'Barrow In Furness', to: 'Carlisle', carriages: 2 },
	{ from: 'Carlisle', to: 'Whitehaven', carriages: 2 },
	{ from: 'Hadfield', to: 'Manchester Piccadilly', carriages: 3 },
	{ from: 'Glossop', to: 'Manchester Piccadilly', carriages: 3 },
	{ from: 'Lincoln Central', to: 'Leicester', carriages: 2 },
	{ from: 'Cleethorpes', to: 'Leicester', carriages: 2 },
	{ from: 'Nottingham', to: 'Leicester', carriages: 2 },
	{ from: 'Avonmouth', to: 'Bristol Temple Meads', carriages: 3 },
	{ from: 'Severn Beach', to: 'Bristol Temple Meads', carriages: 3 },
	{
		from: 'London Liverpool Street',
		to: 'London Stanstead Airport',
		carriages: 12,
	},
	{ from: 'London Liverpool Street', to: 'Norwich', carriages: 12 },
	{ from: 'London Liverpool Street', to: 'Ipswich', carriages: 12 },
	{ from: 'Leicester', to: 'Lincoln Central', carriages: 2 },
	{ from: 'Leicester', to: 'Cleethorpes', carriages: 2 },
	{ from: 'Lincoln Central', to: 'Peterborough', carriages: 2 },
	{ from: 'Lincoln Central', to: 'Sleaford', carriages: 2 },
	{ from: 'Lincoln Central', to: 'Newark North Gate', carriages: 2 },
	{ from: 'Lincoln Central', to: 'Doncaster', carriages: 2 },
	{ from: 'Liverpool Lime Street', to: 'Glasgow Central', carriages: 5 },
	{ from: 'Liverpool Lime Street', to: 'Scarborough', carriages: 5 },
	{ from: 'Manchester Piccadilly', to: 'Scarborough', carriages: 5 },
	{ from: 'Manchester Airport', to: 'Edinburgh Waverley', carriages: 5 },
	{ from: 'Manchester Piccadilly', to: 'Edinburgh Waverley', carriages: 5 },
	{ from: 'Manchester Airport', to: 'Glasgow Central', carriages: 5 },
	{ from: 'Manchester Piccadilly', to: 'Glasgow Central', carriages: 5 },
	{ from: 'Peterborough', to: 'Spalding', carriages: 2 },
	{ from: 'Romsey', to: 'Salisbury', carriages: 2 },
	{ from: 'Exeter', to: 'Honiton', carriages: 2 },
	{ from: 'Exeter', to: 'Axminster', carriages: 2 },
	{ from: 'Brockenhurst', to: 'Lymington Pier', carriages: 4 },
	{ from: 'Rugeley Trent Valley', to: 'Wolverhampton', carriages: 4 },
	{ from: 'Rugeley Trent Valley', to: 'Birmingham New Street', carriages: 4 },
	{
		from: 'Rugeley Trent Valley',
		to: 'Birmingham International',
		carriages: 4,
	},
	{ from: 'Cardiff Central', to: 'Portsmouth Harbour', carriages: 3 },
	{ from: 'Walsall', to: 'Wolverhampton', carriages: 4 },
	{ from: 'Wolverhampton', to: 'Birmingham New Street', carriages: 4 },
	{ from: 'Walsall', to: 'Birmingham New Street', carriages: 4 },
	{ from: 'London Euston', to: 'Shrewsbury', carriages: 5 },
	{
		from: 'Liverpool Lime Street',
		to: 'Birmingham New Street',
		carriages: 8,
	},
	{ from: 'Crewe', to: 'Birmingham New Street', carriages: 4 },
	{ from: 'Stourbridge Junction', to: 'Stourbridge Town', carriages: 1 },
	{ from: 'Watford Junction', to: 'St Albans Abbey', carriages: 4 },
	{ from: 'Four Oaks', to: 'Bromsgrove', carriages: 6 },
	{ from: 'Four Oaks', to: 'Redditch', carriages: 6 },
	{ from: 'Four Oaks', to: 'Birmingham New Street', carriages: 6 },
	{
		from: 'Lichfield Trent Valley',
		to: 'Bromsgrove',
		carriages: 6,
	},
	{ from: 'Lichfield Trent Valley', to: 'Redditch', carriages: 6 },
	{ from: 'Lichfield Trent Valley', to: 'Birmingham New Street', carriages: 6 },
	{ from: 'Lichfield City', to: 'Bromsgrove', carriages: 6 },
	{ from: 'Lichfield City', to: 'Redditch', carriages: 6 },
	{ from: 'Lichfield City', to: 'Birmingham New Street', carriages: 6 },
	{ from: 'Redditch', to: 'Birmingham New Street', carriages: 6 },
	{ from: 'Bromsgrove', to: 'Birmingham New Street', carriages: 6 },
	{ from: 'Bedford', to: 'Bletchley', carriages: 2 },
	{ from: 'Shipley', to: 'Leeds', carriages: 4 },
	{ from: 'Ilkley', to: 'Leeds', carriages: 4 },
	{ from: 'Ilkley', to: 'Bradford Forster Square', carriages: 4 },
	{ from: 'Birmingham Moor Street', to: 'Leamington Spa', carriages: 2 },
	{ from: 'Stratford upon Avon', to: 'Leamington Spa', carriages: 2 },
	{ from: 'Nuneaton', to: 'Leamington Spa', carriages: 2 },
	{ from: 'Kyle of Lochalsh', to: 'Wick', carriages: 2 },
	{ from: 'Anniesland', to: 'Glasgow Queen Street', carriages: 2 },
	{ from: 'Chester', to: 'Crewe', carriages: 2 },
	{
		from: 'Birmingham International',
		to: 'Birmingham New Street',
		carriages: 4,
	},
	{ from: 'Crewe', to: 'Shrewsbury', carriages: 1 },
	{ from: 'Preston', to: 'Ormskirk', carriages: 2 },
	{ from: 'Cardiff Queen Street', to: 'Cardiff Bay', carriages: 1 },
	{ from: 'St Ives', to: 'St Erth', carriages: 2 },
	{ from: 'Machynlleth', to: 'Pwlheli', carriages: 2 },
	{ from: 'Machynlleth', to: 'Aberystwyth', carriages: 2 },
	{ from: 'Saltburn', to: 'Bishop Auckland', carriages: 2 },
	{ from: 'Saltburn', to: 'Darlington', carriages: 2 },
	{ from: 'Blackpool North', to: 'Hazel Grove', carriages: 4 },
	{ from: 'Doncaster', to: 'Leeds', carriages: 4 },
	{ from: 'Bradford Forster Square', to: 'Leeds', carriages: 4 },
	{ from: 'Edinburgh', to: 'London Kings Cross', carriages: 9 },
	{ from: 'Newcastle', to: 'London Kings Cross', carriages: 9 },
	{ from: 'Aberdeen', to: 'London Kings Cross', carriages: 9 },
	{ from: 'Inverness', to: 'London Kings Cross', carriages: 9 },
	{ from: 'Hexham', to: 'Nunthorpe', carriages: 2 },
	{ from: 'Hexham', to: 'Morpeth', carriages: 2 },
	{ from: 'Hexham', to: 'Newcastle', carriages: 2 },
	{ from: 'Carlisle', to: 'Nunthorpe', carriages: 2 },
	{ from: 'Carlisle', to: 'Morpeth', carriages: 2 },
	{ from: 'Carlisle', to: 'Newcastle', carriages: 2 },
	{ from: 'Nunthorpe', to: 'Newcastle', carriages: 2 },
	{ from: 'Morpeth', to: 'Newcastle', carriages: 2 },
	{ from: 'Nunthorpe', to: 'Metrocentre', carriages: 2 },
	{ from: 'Morpeth', to: 'Metrocentre', carriages: 2 },
]

const SNOW_HILL_LINE = {
	'Northbound Direction': [
		{
			destinationName: 'Great Malvern',
			platform: 1,
		},
		{
			destinationName: 'Kidderminster',
			platform: 1,
		},
		{
			destinationName: 'Stourbridge Junction',
			platform: 1,
		},
		{
			destinationName: 'Worcester Foregate Street',
			platform: 1,
		},
		{
			destinationName: 'Worcester Shrub Hill',
			platform: 1,
		},
		{
			destinationName: 'Birmingham Snow Hill',
			platform: 2,
		},
		{
			destinationName: 'Birmingham Moor Street',
			platform: 2,
		},
		{
			destinationName: 'Dorridge',
			platform: 2,
		},
		{
			destinationName: 'Leamington Spa',
			platform: 2,
		},
		{
			destinationName: 'London Marylebone',
			platform: 2,
		},
		{
			destinationName: 'Stratford-upon-Avon',
			platform: 2,
		},
		{
			destinationName: "Whitlock's End",
			platform: 2,
		},
	],
	'Southbound Direction': [
		{
			destinationName: 'Great Malvern',
			platform: 2,
		},
		{
			destinationName: 'Kidderminster',
			platform: 2,
		},
		{
			destinationName: 'Stourbridge Junction',
			platform: 2,
		},
		{
			destinationName: 'Worcester Foregate Street',
			platform: 2,
		},
		{
			destinationName: 'Worcester Shrub Hill',
			platform: 2,
		},
		{
			destinationName: 'Birmingham Snow Hill',
			platform: 1,
		},
		{
			destinationName: 'Birmingham Moor Street',
			platform: 1,
		},
		{
			destinationName: 'Dorridge',
			platform: 1,
		},
		{
			destinationName: 'Leamington Spa',
			platform: 1,
		},
		{
			destinationName: 'London Marylebone',
			platform: 1,
		},
		{
			destinationName: 'Stratford-upon-Avon',
			platform: 1,
		},
		{
			destinationName: "Whitlock's End",
			platform: 1,
		},
	],
}

const CROSS_CITY_NORTH = {
	'Northbound Direction': [
		{
			destinationName: 'Lichfield City',
			platform: 1,
		},
		{
			destinationName: 'Lichfield Trent Valley',
			platform: 1,
		},
		{
			destinationName: 'Four Oaks',
			platform: 1,
		},
		{
			destinationName: 'Barnt Green',
			platform: 2,
		},
		{
			destinationName: 'Birmingham New Street',
			platform: 2,
		},
		{
			destinationName: 'Bromsgrove',
			platform: 2,
		},
		{
			destinationName: 'Longbridge',
			platform: 2,
		},
		{
			destinationName: 'Redditch',
			platform: 2,
		},
	],
	'Southbound Direction': [
		{
			destinationName: 'Barnt Green',
			platform: 1,
		},
		{
			destinationName: 'Birmingham New Street',
			platform: 1,
		},
		{
			destinationName: 'Bromsgrove',
			platform: 1,
		},
		{
			destinationName: 'Longbridge',
			platform: 1,
		},
		{
			destinationName: 'Redditch',
			platform: 1,
		},
		{
			destinationName: 'Four Oaks',
			platform: 2,
		},
		{
			destinationName: 'Lichfield City',
			platform: 2,
		},
		{
			destinationName: 'Lichfield Trent Valley',
			platform: 2,
		},
	],
}

const CROSS_CITY_SOUTH = {
	'Northbound Direction': [
		{
			destinationName: 'Birmingham New Street',
			platform: 1,
		},
		{
			destinationName: 'Derby',
			platform: 1,
		},
		{
			destinationName: 'Leicester',
			platform: 1,
		},
		{
			destinationName: 'Lichfield City',
			platform: 1,
		},
		{
			destinationName: 'Four Oaks',
			platform: 1,
		},
		{
			destinationName: 'Lichfield Trent Valley',
			platform: 1,
		},
		{
			destinationName: 'Nottingham',
			platform: 1,
		},
		{
			destinationName: 'Barnt Green',
			platform: 2,
		},
		{
			destinationName: 'Bromsgrove',
			platform: 2,
		},
		{
			destinationName: 'Cardiff Central',
			platform: 2,
		},
		{
			destinationName: 'Cheltenham Spa',
			platform: 2,
		},
		{
			destinationName: 'Gloucester',
			platform: 2,
		},
		{
			destinationName: 'Hereford',
			platform: 2,
		},
		{
			destinationName: 'Longbridge',
			platform: 2,
		},
		{
			destinationName: 'Redditch',
			platform: 2,
		},
		{
			destinationName: 'Worcester Foregate Street',
			platform: 2,
		},
		{
			destinationName: 'Worcester Shrub Hill',
			platform: 2,
		},
	],
	'Northbound Alt': [
		{
			destinationName: 'Birmingham New Street',
			platform: 1,
		},
		{
			destinationName: 'Derby',
			platform: 1,
		},
		{
			destinationName: 'Leicester',
			platform: 1,
		},
		{
			destinationName: 'Lichfield City',
			platform: 1,
		},
		{
			destinationName: 'Four Oaks',
			platform: 1,
		},
		{
			destinationName: 'Lichfield Trent Valley',
			platform: 1,
		},
		{
			destinationName: 'Nottingham',
			platform: 1,
		},
		{
			destinationName: 'Barnt Green',
			platform: 4,
		},
		{
			destinationName: 'Bromsgrove',
			platform: 4,
		},
		{
			destinationName: 'Cardiff Central',
			platform: 4,
		},
		{
			destinationName: 'Cheltenham Spa',
			platform: 4,
		},
		{
			destinationName: 'Gloucester',
			platform: 4,
		},
		{
			destinationName: 'Hereford',
			platform: 4,
		},
		{
			destinationName: 'Longbridge',
			platform: 4,
		},
		{
			destinationName: 'Redditch',
			platform: 4,
		},
		{
			destinationName: 'Worcester Foregate Street',
			platform: 4,
		},
		{
			destinationName: 'Worcester Shrub Hill',
			platform: 4,
		},
	],
	'Southbound Direction': [
		{
			destinationName: 'Barnt Green',
			platform: 1,
		},
		{
			destinationName: 'Bromsgrove',
			platform: 1,
		},
		{
			destinationName: 'Longbridge',
			platform: 1,
		},
		{
			destinationName: 'Redditch',
			platform: 1,
		},
		{
			destinationName: 'Birmingham New Street',
			platform: 2,
		},
		{
			destinationName: 'Lichfield City',
			platform: 2,
		},
		{
			destinationName: 'Lichfield Trent Valley',
			platform: 2,
		},
		{
			destinationName: 'Four Oaks',
			platform: 2,
		},
	],
}

const CHASE_LINE_SOUTH = {
	'Northbound Direction': [
		{
			destinationName: 'Hednesford',
			platform: 1,
		},
		{
			destinationName: 'Rugeley Trent Valley',
			platform: 1,
		},
		{
			destinationName: 'Walsall',
			platform: 1,
		},
		{
			destinationName: 'Birmingham International',
			platform: 2,
		},
		{
			destinationName: 'Birmingham New Street',
			platform: 2,
		},
		{
			destinationName: 'Coventry',
			platform: 2,
		},
		{
			destinationName: 'Crewe',
			platform: 2,
		},
		{
			destinationName: 'Liverpool Lime Street',
			platform: 2,
		},
		{
			destinationName: 'London Euston',
			platform: 2,
		},
		{
			destinationName: 'Northampton',
			platform: 2,
		},
		{
			destinationName: 'Shrewsbury',
			platform: 2,
		},
		{
			destinationName: 'Wolverhampton',
			platform: 2,
		},
	],
	'Southbound Direction': [
		{
			destinationName: 'Birmingham International',
			platform: 1,
		},
		{
			destinationName: 'Birmingham New Street',
			platform: 1,
		},
		{
			destinationName: 'Coventry',
			platform: 1,
		},
		{
			destinationName: 'Crewe',
			platform: 1,
		},
		{
			destinationName: 'Liverpool Lime Street',
			platform: 1,
		},
		{
			destinationName: 'London Euston',
			platform: 1,
		},
		{
			destinationName: 'Northampton',
			platform: 1,
		},
		{
			destinationName: 'Shrewsbury',
			platform: 1,
		},
		{
			destinationName: 'Wolverhampton',
			platform: 1,
		},
		{
			destinationName: 'Hednesford',
			platform: 2,
		},
		{
			destinationName: 'Rugeley Trent Valley',
			platform: 2,
		},
		{
			destinationName: 'Walsall',
			platform: 2,
		},
	],
}

const CHASE_LINE_NORTH = {
	'Northbound Direction': [],
	'Southbound Direction': [
		{
			destinationName: 'Birmingham International',
			platform: 1,
		},
		{
			destinationName: 'Birmingham New Street',
			platform: 1,
		},
		{
			destinationName: 'Coventry',
			platform: 1,
		},
		{
			destinationName: 'Crewe',
			platform: 1,
		},
		{
			destinationName: 'Liverpool Lime Street',
			platform: 1,
		},
		{
			destinationName: 'London Euston',
			platform: 1,
		},
		{
			destinationName: 'Northampton',
			platform: 1,
		},
		{
			destinationName: 'Shrewsbury',
			platform: 1,
		},
		{
			destinationName: 'Wolverhampton',
			platform: 1,
		},
		{
			destinationName: 'Hednesford',
			platform: 2,
		},
		{
			destinationName: 'Rugeley Trent Valley',
			platform: 2,
		},
		{
			destinationName: 'Walsall',
			platform: 2,
		},
	],
}

const STOUR_VALLEY_LINE = {
	'Southbound Direction': [
		{
			destinationName: 'Birmingham International',
			platform: 1,
		},
		{
			destinationName: 'Birmingham New Street',
			platform: 1,
		},
		{
			destinationName: 'Coventry',
			platform: 1,
		},
		{
			destinationName: 'London Euston',
			platform: 1,
		},
		{
			destinationName: 'Northampton',
			platform: 1,
		},
		{
			destinationName: 'Rugeley Trent Valley',
			platform: 1,
		},
		{
			destinationName: 'Walsall',
			platform: 1,
		},
		{
			destinationName: 'Blackpool North',
			platform: 2,
		},
		{
			destinationName: 'Carlisle',
			platform: 2,
		},
		{
			destinationName: 'Crewe',
			platform: 2,
		},
		{
			destinationName: 'Edinburgh Waverley',
			platform: 2,
		},
		{
			destinationName: 'Glasgow Central',
			platform: 2,
		},
		{
			destinationName: 'Lancaster',
			platform: 2,
		},
		{
			destinationName: 'Liverpool Lime Street',
			platform: 2,
		},
		{
			destinationName: 'Manchester Piccadilly',
			platform: 2,
		},
		{
			destinationName: 'Preston',
			platform: 2,
		},
		{
			destinationName: 'Shrewsbury',
			platform: 2,
		},
		{
			destinationName: 'Wolverhampton',
			platform: 2,
		},
	],
}

export const SINGLE_PLATFORM_FALLBACKS = [
	'Aberdare',
	'Aberdovey',
	'Abererch',
	'Achanalt',
	'Achnashellach',
	'Alexandria',
	'Alloa',
	'Alness',
	'Althorne',
	'Altnabreac',
	'Ambergate',
	'Ammanford',
	'Anderston',
	'Ansdell and Fairhaven',
	'Ardrossan Harbour',
	'Ardrossan South Beach',
	'Ardrossan Town',
	'Attadale',
	'Aylesbury Vale Parkway',
	'Baildon',
	'Balloch',
	'Banavie',
	'Banstead',
	'Barnstaple',
	'Barry Island',
	'Barton-on-Humber',
	'Battersby',
	'Battlesbridge',
	'Bearley',
	'Beasdale',
	'Beauly',
	'Bedford St Johns',
	'Belmont',
	'Bere Alston',
	'Bere Ferrers',
	'Berney Arms',
	'Berry Brow',
	'Betws-y-Coed',
	'Birbeck ',
	'Birchgrove',
	'Bishop Auckland',
	'Blackpool Pleasure Beach',
	'Blackpool South',
	'Blaenau Ffestiniog',
	'Borth',
	'Bow Street',
	'Braintree Freeport',
	'Braintree',
	'Brampton',
	'Branchton',
	'Braystones',
	'Bricket Wood',
	'Brierfield',
	'Brockholes',
	'Broome',
	'Brunstane',
	'Bucknell',
	'Bugle',
	'Bulwell ',
	'Builth Road',
	'Bures',
	'Burneside',
	'Burnham-On-Crouch',
	'Burnley Barracks',
	'Burnley Central',
	'Burscough Junction',
	'Buxted',
	'Caersws',
	'Calstock',
	'Carbis Bay',
	'Cardiff Bay',
	'Castleford',
	'Castleton Moor',
	'Causeland',
	'Chafford Hundred',
	'Chandlers Ford',
	'Chapleton',
	'Chappel and Wakes Colne',
	'Chessington South',
	'Chetnole',
	'Cilmeri',
	'Claverdon',
	'Colchester Town',
	'Colne',
	'Colwall',
	'Combe Halt',
	'Commondale',
	'Connel Ferry',
	'Conon Bridge',
	'Cookham',
	'Coombe',
	'Copplestone',
	'Corby',
	'Corkerhill',
	'Corkickle',
	'Corpach',
	'Corrour',
	'Coryton',
	'Cowden ',
	'Craigendoran',
	'Cranbrook',
	'Cressing',
	'Crewkerne',
	'Criccieth',
	'Cromford',
	'Crookston',
	'Croston',
	'Croxley Green',
	'Culrain',
	'Cwmbach',
	'Cynghordy',
	'Danby',
	'Denby Dale',
	'Digby and Sowton',
	'Dinas Rhondda',
	'Dingle Road',
	'Dodworth',
	'Dolau',
	'Doleham',
	'Dolgarrog',
	'Dolwyddelan',
	'Dore',
	'Dovercourt',
	'Drumfrochar',
	'Duirnish',
	'Duncraig',
	'Dunlop',
	'Dunrobin',
	'Dyffryn Ardudwy',
	'East Kilbride',
	'Ebbw Vale Parkway',
	'Egton',
	'Emerson Park',
	'Entwistle',
	'Epsom Downs',
	'Eridge ',
	'Exmouth',
	'Exton',
	'Fairbourne',
	'Fairlie',
	'Falls of Cruachan',
	'Falmouth Docks',
	'Falmouth Town',
	'Fearn',
	'Felixstowe Town',
	'Feniton',
	'Fenny Stratford',
	'Fernhill',
	'Ffairfach',
	'Finstock',
	'Fishguard Harbour',
	'Forres',
	'Frinton',
	'Frome',
	'Furze Platt',
	'Garston (Herts)',
	'Garth (Mid Glamorgan)',
	'Garth',
	'Georgemas',
	'Glan Conwy',
	'Glossop',
	'Golspie',
	'Great Ayton',
	'Greenford',
	'Grimsby Docks',
	'Grosmont',
	'Gunnislake',
	'Gunton',
	'Hadfield',
	'Hairmyres',
	'Hanborough',
	'Harwich Town',
	'Hawkhead',
	'Helensburgh Upper',
	'Henley-on-Thames',
	'Heysham Port',
	'Honley',
	'Hopton Heath',
	'How Wood',
	'Hucknall',
	'IBM',
	'Inverkip',
	'Invershin',
	'James Cook',
	'Johnston (Dyfed)',
	'Keith',
	'Kelvindale',
	'Kendal',
	'Kenilworth',
	'Kildale',
	'Kildonan',
	'Kilgetty',
	'Kilmaurs',
	'Kinbrace',
	'Kings Nympton',
	'Kirton Lindsey',
	'Knucklas',
	'Lamphey',
	'Lapford',
	'Lealholm',
	'Lelant Saltings',
	'Lelant',
	'Lingwood',
	'Little Kimble',
	'Llanaber',
	'Llanbedr',
	'Llanbister Road',
	'Llandanwg',
	'Llandecwyn',
	'Llandybie',
	'Llangadog',
	'Llangammarch',
	'Llangynllo',
	'Llanhilleth',
	'Llanrwst',
	'Llanwrda',
	'Llwyngwril',
	'Llwynypia',
	'Lochailort',
	'Loch Awe',
	'Loch Eil Outward Bound',
	'Locheilside',
	'Lochluichart',
	'Lockwood',
	'Looe',
	'Luxulyan',
	'Lymington Pier',
	'Lymington Town',
	'Lympstone Commando',
	'Lympstone Village',
	'Lytham',
	'Maesteg (Ewenny Road)',
	'Maesteg',
	'Malton',
	'Manchester United Halt',
	'Manorbier',
	'Marlow',
	'Marton',
	'Maryport',
	'Matlock Bath',
	'Maybole',
	'Melksham',
	'Melton',
	'Merthyr Tydfil',
	'Merthyr Vale',
	'Milford Haven',
	'Milnrow',
	'Minffordd',
	'Monks Risborough',
	'Montpelier',
	'Morar',
	'Morchard Road',
	'Morfa Mawddach',
	'Mosspark',
	'Moss Side',
	'Narberth',
	'Navigation Road',
	'Nelson',
	'Nethertown',
	'Newbridge',
	'New Clee',
	'Newcraighall',
	'New Hey',
	'New Holland',
	'Newmarket',
	'Newquay',
	'Newstead',
	'Newtonmore',
	'Newton St Cyres',
	'North Berwick',
	'North Road',
	'Ormskirk',
	'Oulton Broad South',
	'Paisley Canal',
	'Pantyffynnon',
	'Parkgate',
	'Park Street',
	'Pembroke Dock',
	'Pembroke',
	'Penally',
	'Penarth',
	'Penhelig',
	'Penmere',
	'Penrhiwceiber',
	'Penrhyndeudraeth',
	'Penryn',
	'Pensarn',
	'Pentre Bach',
	'Pen-y-Bont',
	'Penychain',
	'Perranwell',
	'Pershore',
	'Pilning',
	'Plockton',
	'Polesworth',
	'Polsoe Bridge',
	'Pontarddulais',
	'Pont-y-Pant',
	'Portsmouth Arms',
	'Pwllheli',
	"Quaker's Yard",
	'Quintrel Downs',
	'Reddish South',
	'Redditch',
	'Redland',
	'Renton',
	'Rhiwbina',
	'Roche',
	'Rogerstone',
	'Roman Bridge',
	'Rose Hill Marple',
	'Roughton Road',
	'Roy Bridge',
	'Ruswarp',
	'Sampford Courtenay',
	'Sandplace',
	'Sarn',
	'Saundersfoot',
	'Scotscalder',
	'Sea Mills',
	'Severn Beach',
	'Shanklin',
	'Shepperton',
	'Sheringham',
	'Shiplake',
	'Shirehampton',
	'Silkstone Common',
	'Silvertown',
	'Sleights',
	'Smallbrook Junction',
	'Snaith',
	'South Hylton',
	'Southminster',
	'Squires Gate',
	'St Albans Abbey',
	'St Andrews Road',
	'St Annes-on-the-Sea',
	'Staveley',
	'St Budeaux Victoria Road',
	'St Columb Road',
	'Stewarton',
	'St Ives',
	'St Keyne',
	'Stourbridge Town',
	'Stromeferry',
	'Sudbury',
	'Sugar Loaf',
	'Swale',
	'Syston',
	'Talsarnau',
	'Talybont',
	'Tal-y-Cafn',
	'Templecombe',
	'Teeside Airport',
	'Thornford',
	'Thorntonhall',
	'Three Oaks',
	'Thurso',
	'Tir-Phil',
	'Tisbury',
	'Tondu',
	'Tonfanau',
	'Ton Pentre',
	'Tonypandy',
	'Treherbert',
	'Treorchy',
	'Trimley',
	'Troed-y-Rhiw',
	'Ty Glas',
	'Tygwyn',
	'Tyndrum Lower',
	'Uckfield',
	'Ulceby',
	'Umberleigh',
	'Upper Tyndrum',
	'Wadsley Bridge',
	'Walton-On-Naze',
	'Ware',
	'Wargrave',
	'Watford North',
	'West Kilbride',
	'Weston Milton',
	'West Runton',
	'Whatstandwell',
	'Whimple',
	'Whinhill',
	'Whitchurch (S. Glam)',
	'White Notley',
	'Wickham Market',
	'Wick',
	'Wildmill',
	'Winchelsea',
	'Windermere',
	'Windsor and Eton Central',
	'Woodham Ferrers',
	'Worstead',
	'Wrexham Central',
	'Yeoford',
	'Yetminster',
	'Ynyswen',
]

export const SPECIFIC_PLATFORM_FALLBACKS = {
	Aston: [
		...CROSS_CITY_NORTH['Northbound Direction'],
		...CHASE_LINE_SOUTH['Northbound Direction'],
	],
	'Bescot Stadium': CHASE_LINE_SOUTH['Southbound Direction'],
	Blakedown: SNOW_HILL_LINE['Northbound Direction'],
	'Blake Street': CROSS_CITY_NORTH['Southbound Direction'],
	"Butler's Lane": CROSS_CITY_NORTH['Southbound Direction'],
	Bloxwich: CHASE_LINE_NORTH['Southbound Direction'],
	'Bloxwich North': CHASE_LINE_NORTH['Southbound Direction'],
	Bournville: CROSS_CITY_SOUTH['Northbound Direction'],
	Cannock: CHASE_LINE_NORTH['Southbound Direction'],
	'Chester Road': CROSS_CITY_NORTH['Northbound Direction'],
	'Cradley Heath': SNOW_HILL_LINE['Southbound Direction'],
	Coseley: STOUR_VALLEY_LINE['Southbound Direction'],
	Danzey: SNOW_HILL_LINE['Southbound Direction'],
	Duddeston: [
		...CROSS_CITY_NORTH['Southbound Direction'],
		...CHASE_LINE_SOUTH['Southbound Direction'],
	],
	'Dudley Port': STOUR_VALLEY_LINE['Southbound Direction'],
	'Old Hill': SNOW_HILL_LINE['Southbound Direction'],
	Earlswood: SNOW_HILL_LINE['Southbound Direction'],
	Erdington: CROSS_CITY_NORTH['Northbound Direction'],
	'Five Ways': CROSS_CITY_SOUTH['Northbound Direction'],
	'Gravelly Hill': CROSS_CITY_NORTH['Southbound Direction'],
	Hagley: SNOW_HILL_LINE['Northbound Direction'],
	'The Hawthorns': SNOW_HILL_LINE['Northbound Direction'],
	'Hall Green': SNOW_HILL_LINE['Southbound Direction'],
	Hamstead: CHASE_LINE_SOUTH['Southbound Direction'],
	Hednesford: CHASE_LINE_NORTH['Southbound Direction'],
	'Henley-in-Arden': SNOW_HILL_LINE['Southbound Direction'],
	'Jewellery Quarter': SNOW_HILL_LINE['Northbound Direction'],
	Kidderminster: SNOW_HILL_LINE['Southbound Direction'],
	'Kings Norton': CROSS_CITY_SOUTH['Northbound Alt'],
	'The Lakes': SNOW_HILL_LINE['Southbound Direction'],
	Landywood: CHASE_LINE_NORTH['Southbound Direction'],
	'Langley Green': SNOW_HILL_LINE['Northbound Direction'],
	Longbridge: CROSS_CITY_SOUTH['Northbound Direction'],
	'Lichfield City': CROSS_CITY_NORTH['Northbound Direction'],
	Lye: SNOW_HILL_LINE['Northbound Direction'],
	Northfield: CROSS_CITY_SOUTH['Northbound Alt'],
	'Rowley Regis': SNOW_HILL_LINE['Southbound Direction'],
	'Sandwell and Dudley': STOUR_VALLEY_LINE['Southbound Direction'],
	Shirley: SNOW_HILL_LINE['Southbound Direction'],
	Shenstone: CROSS_CITY_NORTH['Northbound Direction'],
	'Selly Oak': CROSS_CITY_SOUTH['Northbound Direction'],
	'Smethwick Rolfe Street': STOUR_VALLEY_LINE['Southbound Direction'],
	'Spring Road': SNOW_HILL_LINE['Southbound Direction'],
	'Sutton Coldfield': CROSS_CITY_NORTH['Northbound Direction'],
	'Tame Bridge Parkway': CHASE_LINE_SOUTH['Southbound Direction'],
	Tipton: STOUR_VALLEY_LINE['Southbound Direction'],
	University: CROSS_CITY_SOUTH['Northbound Direction'],
	Witton: CHASE_LINE_SOUTH['Southbound Direction'],
	'Wood End': SNOW_HILL_LINE['Southbound Direction'],
	'Wootton Wawen': SNOW_HILL_LINE['Southbound Direction'],
	'Wylde Green': CROSS_CITY_NORTH['Northbound Direction'],
	Wythall: SNOW_HILL_LINE['Northbound Direction'],
	'Yardley Wood': SNOW_HILL_LINE['Southbound Direction'],
	'Smethwick Galton Bridge': [
		{ destinationName: 'Wolverhampton', platform: '3' },
		{ destinationName: 'Liverpool Lime Street', platform: '3' },
		{ destinationName: 'Crewe', platform: '3' },
		{ destinationName: 'Aberystwyth', platform: '3' },
		{ destinationName: 'Shrewsbury', platform: '3' },
		{ destinationName: 'Chester', platform: '3' },
		{ destinationName: 'Holyhead', platform: '3' },
		{ destinationName: 'Llandundo', platform: '3' },
		{ destinationName: 'Llandundo Junction', platform: '3' },
		{ destinationName: 'Manchester Piccadilly', platform: '3' },
		{ destinationName: 'Pwlheli', platform: '3' },
		{ destinationName: 'Birmingham New Street', platform: '4' },
		{ destinationName: 'Birmingham International', platform: '4' },
		{ destinationName: 'Coventry', platform: '4' },
		{ destinationName: 'London Euston', platform: '4' },
		{ destinationName: 'Northampton', platform: '4' },
		{ destinationName: 'Rugeley Trent Valley', platform: '4' },
		{ destinationName: 'Walsall', platform: '4' },
	],
	'Lichfield Trent Valley': [
		{ destinationName: 'Crewe', platform: '1' },
		{ destinationName: 'Chester', platform: '1' },
		{ destinationName: 'Glasgow Central', platform: '1' },
		{ destinationName: 'Holyhead', platform: '1' },
		{ destinationName: 'Liverpool Lime Street', platform: '1' },
		{ destinationName: 'Manchester Piccadilly', platform: '1' },
		{ destinationName: 'Preston', platform: '1' },
		{ destinationName: 'Stafford', platform: '1' },
		{ destinationName: 'Stoke on Trent', platform: '1' },
		{ destinationName: 'London Euston', platform: '2' },
		{ destinationName: 'Milton Keynes Central', platform: '2' },
		{ destinationName: 'Northampton', platform: '2' },
		{ destinationName: 'Nuneaton', platform: '2' },
		{ destinationName: 'Rugby', platform: '2' },
		{ destinationName: 'Birmingham New Street', platform: '3' },
		{ destinationName: 'Bromsgrove', platform: '3' },
		{ destinationName: 'Longbridge', platform: '3' },
		{ destinationName: 'Redditch', platform: '3' },
	],
	'Rugeley Trent Valley': [
		{ destinationName: 'Birmingham New Street', platform: '1' },
		{ destinationName: 'Birmingham International', platform: '1' },
		{ destinationName: 'Coventry', platform: '1' },
		{ destinationName: 'Wolverhampton', platform: '1' },
		{ destinationName: 'Crewe', platform: '2' },
		{ destinationName: 'Stafford', platform: '2' },
		{ destinationName: 'Stoke on Trent', platform: '2' },
		{ destinationName: 'London Euston', platform: '3' },
		{ destinationName: 'Milton Keynes Central', platform: '3' },
		{ destinationName: 'Northampton', platform: '3' },
		{ destinationName: 'Nuneaton', platform: '3' },
		{ destinationName: 'Rugby', platform: '3' },
	],
	'Heath High Level': [
		{ destinationName: 'Bargoed', platform: '1' },
		{ destinationName: 'Caerphilly', platform: '1' },
		{ destinationName: 'Rhymney', platform: '1' },
		{ destinationName: 'Ystrad Mynach', platform: '1' },
		{ destinationName: 'Barry Island', platform: '2' },
		{ destinationName: 'Bridgend', platform: '2' },
		{ destinationName: 'Cardiff Bay', platform: '2' },
		{ destinationName: 'Cardiff Central', platform: '2' },
		{ destinationName: 'Cardiff Queen Street', platform: '2' },
		{ destinationName: 'Penarth', platform: '2' },
	],
	'London St Pancras International': [
		{
			destinationName: 'Three Bridges',
			platform: 'A',
		},
		{
			destinationName: 'Brighton',
			platform: 'A',
		},
		{
			destinationName: 'Gatwick Airport',
			platform: 'A',
		},
		{
			destinationName: 'Bedford',
			platform: 'B',
		},
		{
			destinationName: 'Peterborough',
			platform: 'B',
		},
		{
			destinationName: 'St Albans City',
			platform: 'B',
		},
	],
	Tamworth: [
		{ destinationName: 'Chester', platform: '1' },
		{ destinationName: 'Crewe', platform: '1' },
		{ destinationName: 'Holyhead', platform: '1' },
		{ destinationName: 'Liverpool Lime Street', platform: '1' },
		{ destinationName: 'Manchester Piccadilly', platform: '1' },
		{ destinationName: 'Preston', platform: '1' },
		{ destinationName: 'Stafford', platform: '1' },
		{ destinationName: 'Stoke on Trent', platform: '1' },
		{
			destinationName: 'Glasgow Central',
			originName: 'London Euston',
		},
		{ destinationName: 'London Euston', platform: '2' },
		{ destinationName: 'Milton Keynes Central', platform: '2' },
		{ destinationName: 'Northampton', platform: '2' },
		{ destinationName: 'Nuneaton', platform: '2' },
		{ destinationName: 'Rugby', platform: '2' },
		{ destinationName: 'Aberdeen', platform: '3' },
		{ destinationName: 'Derby', platform: '3' },
		{ destinationName: 'Dundee', platform: '3' },
		{ destinationName: 'Doncaster', platform: '3' },
		{ destinationName: 'Edinburgh', platform: '3' },
		{ destinationName: 'Leeds', platform: '3' },
		{ destinationName: 'Newcastle', platform: '3' },
		{ destinationName: 'Nottingham', platform: '3' },
		{ destinationName: 'York', platform: '3' },
		{
			destinationName: 'Glasgow Central',
			originName: 'Birmingham New Street',
			platform: '3',
		},
		{
			destinationName: 'Glasgow Central',
			originName: 'Bristol Temple Meads',
			platform: '3',
		},
		{
			destinationName: 'Glasgow Central',
			originName: 'Exeter St Davids',
			platform: '3',
		},
		{
			destinationName: 'Glasgow Central',
			originName: 'Penzance',
			platform: '3',
		},
		{
			destinationName: 'Glasgow Central',
			originName: 'Plymouth',
			platform: '3',
		},
		{ destinationName: 'Birmingham New Street', platform: '4' },
		{ destinationName: 'Bristol Temple Meads', platform: '4' },
		{ destinationName: 'Cardiff Central', platform: '4' },
		{ destinationName: 'Exeter St Davids', platform: '4' },
		{ destinationName: 'Newquay', platform: '4' },
		{ destinationName: 'Newport', platform: '4' },
		{ destinationName: 'Paignton', platform: '4' },
		{ destinationName: 'Penzance', platform: '4' },
		{ destinationName: 'Plymouth', platform: '4' },
	],
	Radyr: [
		{ destinationName: 'Barry Island', platform: '1' },
		{ destinationName: 'Bridgend', platform: '1' },
		{ destinationName: 'Cardiff Queen Street', platform: '1' },
		{ destinationName: 'Penarth', platform: '1' },
		{
			destinationName: 'Cardiff Central',
			originName: 'Aberdare',
			platform: '1',
		},
		{
			destinationName: 'Cardiff Central',
			originName: 'Methyr Tydfil',
			platform: '1',
		},
		{
			destinationName: 'Cardiff Central',
			originName: 'Pontypridd',
			platform: '1',
		},
		{
			destinationName: 'Cardiff Central',
			originName: 'Treherbert',
			platform: '1',
		},
		{ destinationName: 'Aberdare', platform: '2' },
		{ destinationName: 'Methyr Tydfil', platform: '2' },
		{ destinationName: 'Pontypridd', platform: '2' },
		{ destinationName: 'Treherbert', platform: '2' },
		{ destinationName: 'Coryton', platform: '3' },
		{
			destinationName: 'Cardiff Central',
			originName: 'Radyr',
			platform: '3',
		},
	],
}

export const LONDON_NORTHWESTERN_RAILWAY = [
	'London Euston',
	'Rugeley Trent Valley',
	'Northampton',
	'Crewe',
	'Liverpool Lime Street',
]

export const FIRST_CLASS_OPERATORS = [
	'Avanti West Coast',
	'CrossCountry',
	'Gatwick Express',
	'Grand Central',
	'Heathrow Express',
	'Hull Trains',
	'London Northwestern Railway',
	'LNER',
	'Transpennine Express',
]

export const DOUBLE_FALSE = [false, false]
